### PR TITLE
Fix build, Makefile, rdef, new screenshot

### PR DESCRIPTION
**Pull request by BachToTheFuture**
Solves #2.
Colors! didn't seem to have a Makefile, so made one 😄 
Other changes:
* fixed build on x86_64, because it wouldn't build
* replaced .rsrc with .rdef
* added new screenshot, because Colors in HaikuArchives is different from the one in HaikuDepot.

This is what Colors! looks like in HaikuArchives:

colors

### CODE REVIEW

**Comment by BachToTheFuture** [comment]
Hmmm... @scottmc apparently there's a different version of Colors in https://github.com/jscipione/Colors, and this is the one on HaikuDepot.

Where did this one come from?

**Comment by humdingerb** [comment]
Yep. This here is the original Colors! before John did all those changes that made it waht it is today (in his repo). IMO it should be removed from HaikuArchives, as John has clearly adopted the project years ago.

Which means bach5000's work was for naught. :(
I recommend accepting it for his GCI task, as it's not his fault...

**Comment by scottmc** [comment]
Readme should then be updated to point to John's version.  Yes, we can mark this as completed.

**Comment by BachToTheFuture** [comment]
@humdingerb @scottmc Done!
Oops. Sorry for working on the wrong version of Colors :(

**Comment by scottmc** [comment]
No worries. I didn't know there was a more active fork.

**Comment by BachToTheFuture** [comment]
@humdingerb @scottmc Could you check my GCI task?
Thank you guys for being so nice!

**Pull request merged**
